restaurants = [{
        restaurant_id: "123",
        restaurantName: "McDonalds",
        apartmentNumber: 411,
        streetname: "4th Street",
        zipcode: 20007,
        phoneNumber: 5062147483,
        imgUrl: "https://i1.wp.com/www.eatthis.com/wp-content/uploads/2018/12/the-golden-mcdonalds-arch.jpg?fit=1200%2C879&ssl=1",
        rating: 4.8,
        tags: ["burgers", "fries", "shakes"],
        menu: [{
                name: "Whopper",
                description: "Delicious Burger",
                imgURL: "https://media1.s-nbcnews.com/j/newscms/2019_21/2870431/190524-classic-american-cheeseburger-ew-207p_d9270c5c545b30ea094084c7f2342eb4.fit-1240w.jpg",
                price: 4.75,
            },
            {
                name: "chicken nuggets",
                description: "https://i.insider.com/5f74ca460ab50d00184ad5ac?width=1100&format=jpeg&auto=webp",
                price: 6.25,
            },
            {
                name: "fries",
                description: "golden fries",
                imgURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNsQDPub_KpLRPdFPUjuKZ_2DdvDhUzmLrgg&usqp=CAU",
                price: 6.25,
            },
        ],
    },

    {
        restaurant_id: "456",
        restaurantName: "Pizza Hut",
        apartmentNumber: 600,
        streetname: "Elm Rd",
        zipcode: 47301,
        phoneNumber: 5849601022,
        imgUrl: "https://d1ralsognjng37.cloudfront.net/3c2c3cf2-143e-42da-9c05-fca34d50cfd3.jpeg",
        rating: 4.2,
        tags: ["pizza", "pasta", "garlic bread"],
        menu: [{
                name: "Medium Pizza",
                description: "Yummy Pizza",
                imgURL: "https://d1ralsognjng37.cloudfront.net/dc17742c-1eb5-4afd-b888-08aaa4d62160.jpeg",
                price: 20,
            },
            {
                name: "Garlic Toast ",
                description: "Yummy garlic toast",
                imgURL: "https://d1ralsognjng37.cloudfront.net/dc17742c-1eb5-4afd-b888-08aaa4d62160.jpeg",
                price: 7.5,
            },
        ],
    },

    {
        restaurant_id: "111",
        restaurantName: "Subway",
        apartmentNumber: 600,
        streetname: "5th St",
        zipcode: 12343,
        phoneNumber: 5749229084,
        imgUrl: "https://www.subway.com/-/media/Base_English/Images/Branding/subway-logo-new-1200x630.png",
        rating: 3.1,
        tags: ["sandwich", "salad", "vegan"],
        menu: [{
            name: "turkey sandwich",
            description: "fresh and delicous turkey sandwich",
            imgURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNsQDPub_KpLRPdFPUjuKZ_2DdvDhUzmLrgg&usqp=CAU",
            price: 9,
        }, ],
    },

    {
        restaurant_id: "222",
        restaurantName: "KFC",
        apartmentNumber: 100,
        streetname: "Klien St",
        zipcode: 47382,
        phoneNumber: 3754320798,
        imgUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/KFC_logo.svg/200px-KFC_logo.svg.png",
        rating: 2.5,
        tags: ["fried chicken"],
        menu: [{
            name: "fries",
            description: "golden fries",
            imgURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkKRWRjRH61xUf2NENx8gF0QwQIddbuwES0g&usqp=CAU",
            price: 10,
        }, ],
    },
    {
        restaurant_id: "789",
        restaurantName: "Taco Bell",
        apartmentNumber: 523,
        streetname: "Glover Dr",
        zipcode: 43321,
        phoneNumber: 5849312344,
        imgUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b3/Taco_Bell_2016.svg/150px-Taco_Bell_2016.svg.png",
        rating: 3.1,
        tags: ["tacos", "burritos", "quesadillas"],
        menu: [{
                name: "Three Tacos",
                description: "Delicous Tacos",
                imgURL: "https://www.tacobell.com/medias/taco-bell-grilled-cheese-burrito.jpg?context=bWFzdGVyfGltYWdlc3wxNjQ2NDd8aW1hZ2UvanBlZ3xpbWFnZXMvaGFkL2gzZC84OTk0MDY0MzY3NjQ2LmpwZ3w0YzJjNTMxNDE3NWQ4MzcxOGY3MmUzMDM1ZTE0NDM3OTdkOTZmMTBhZjkyM2JjYjIwYWIzYTI1MmQ0MzdhNWVh",
                price: 2.7,
            },
            {
                name: "Quesadilla",
                description: "Delicious Quesadilla",
                imgURL: "https://www.tacobell.com/medias/taco-bell-grilled-cheese-burrito.jpg?context=bWFzdGVyfGltYWdlc3wxNjQ2NDd8aW1hZ2UvanBlZ3xpbWFnZXMvaGFkL2gzZC84OTk0MDY0MzY3NjQ2LmpwZ3w0YzJjNTMxNDE3NWQ4MzcxOGY3MmUzMDM1ZTE0NDM3OTdkOTZmMTBhZjkyM2JjYjIwYWIzYTI1MmQ0MzdhNWVh",
                price: 8,
            },
            {
                name: "burrito",
                description: "Delicious burrito",
                imgURL: "https://www.tacobell.com/medias/taco-bell-grilled-cheese-burrito.jpg?context=bWFzdGVyfGltYWdlc3wxNjQ2NDd8aW1hZ2UvanBlZ3xpbWFnZXMvaGFkL2gzZC84OTk0MDY0MzY3NjQ2LmpwZ3w0YzJjNTMxNDE3NWQ4MzcxOGY3MmUzMDM1ZTE0NDM3OTdkOTZmMTBhZjkyM2JjYjIwYWIzYTI1MmQ0MzdhNWVh",
                price: 6.25,
            },
        ],
    },
];

module.exports = restaurants;
