restaurants = [{
        restaurant_id: "123",
        restaurantName: "McDonalds",
        apartmentNumber: 411,
        streetname: "4th Street",
        zipcode: 20007,
        phoneNumber: 5062147483,
        imgUrl: "https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/exps28800_UG143377D12_18_1b_RMS.jpg",
        rating: 4.8,
        tags: ["burgers", "fries", "shakes"],
        menu: [],
    },

    {
        restaurant_id: "456",
        restaurantName: "Pizza Hut",
        apartmentNumber: 600,
        streetname: "Elm Rd",
        zipcode: 47301,
        phoneNumber: 5849601022,
        imgUrl: "https://image.freepik.com/free-photo/mixed-pizza-with-various-ingridients_140725-3790.jpg",
        rating: 4.2,
        tags: ["pizza", "pasta", "garlic bread"],
        menu: [],
    },

    {
        restaurant_id: "111",
        restaurantName: "Subway",
        apartmentNumber: 600,
        streetname: "5th St",
        zipcode: 12343,
        phoneNumber: 5749229084,
        imgUrl: "https://image.freepik.com/free-photo/fresh-tasty-sandwich_144627-15298.jpg",
        rating: 3.1,
        tags: ["sandwich", "salad", "vegan"],
        menu: [],
    },

    {
        restaurant_id: "222",
        restaurantName: "KFC",
        apartmentNumber: 100,
        streetname: "Klien St",
        zipcode: 47382,
        phoneNumber: 3754320798,
        imgUrl: "https://image.freepik.com/free-photo/crispy-fried-chicken-plate-with-salad-carrot_1150-20212.jpg",
        rating: 2.5,
        tags: ["fried chicken"],
        menu: [],
    },
    {
        restaurant_id: "789",
        restaurantName: "Taco Bell",
        apartmentNumber: 523,
        streetname: "Glover Dr",
        zipcode: 43321,
        phoneNumber: 5849312344,
        imgUrl: "https://image.freepik.com/free-photo/tacos-is-traditional-mexican-dish-tortilla-stuffed-with-chicken-bell-hot-peppers-beans-lettuce-cheese-blue-onion-with-salsa-sauce-white-wooden-background-top-view-close-up_193819-741.jpg",
        rating: 3.1,
        tags: ["tacos", "burritos", "quesadillas"],
        menu: [],
    },
    {
        restaurant_id: "888",
        restaurantName: "Ciao Bella",
        apartmentNumber: 900,
        streetname: "Brown Circle",
        zipcode: 44311,
        phoneNumber: 1987654346,
        imgUrl: "https://www.thedailymeal.com/sites/default/files/2020/01/13/bestitalina-main-istock.jpg",
        rating: 3.1,
        tags: ["pizza", "pasta", "wine"],
        menu: [],
    },
    {
        restaurant_id: "999",
        restaurantName: "Hünkar",
        apartmentNumber: 123,
        streetname: "7th Street",
        zipcode: 46371,
        phoneNumber: 1987658474,
        imgUrl: "https://image.freepik.com/free-photo/turkish-pide-with-minced-meat-kiymali-pide-traditional-turkish-cuisine-turkish-pizza-pita-with-meat-top-view-overhead_2829-20272.jpg",
        rating: 3.1,
        tags: ["Mediterranean", "Balkan cuisine"],
        menu: [],
    },
    {
        restaurant_id: "777",
        restaurantName: "Adda",
        apartmentNumber: 876,
        streetname: "9th Street",
        zipcode: 88371,
        phoneNumber: 9868765847,
        imgUrl: "https://assets3.thrillist.com/v1/image/2798288/1584x3000/scale;jpeg_quality=60.jpg",
        rating: 3.1,
        tags: ["Indian cuisine"],
        menu: [],
    },
];

module.exports = restaurants;