restaurants = [{
        restaurant_id: "123",
        restaurantName: "McDonalds",
        apartmentNumber: 411,
        streetname: "4th Street",
        zipcode: 20007,
        phoneNumber: 5062147483,
        imgUrl: "https://i1.wp.com/www.eatthis.com/wp-content/uploads/2018/12/the-golden-mcdonalds-arch.jpg?fit=1200%2C879&ssl=1",
        rating: 4.8,
        tags: ["burgers", "fries", "shakes"],
        menu: [],
    },

    {
        restaurant_id: "456",
        restaurantName: "Pizza Hut",
        apartmentNumber: 600,
        streetname: "Elm Rd",
        zipcode: 47301,
        phoneNumber: 5849601022,
        imgUrl: "https://d1ralsognjng37.cloudfront.net/3c2c3cf2-143e-42da-9c05-fca34d50cfd3.jpeg",
        rating: 4.2,
        tags: ["pizza", "pasta", "garlic bread"],
        menu: [],
    },

    {
        restaurant_id: "111",
        restaurantName: "Subway",
        apartmentNumber: 600,
        streetname: "5th St",
        zipcode: 12343,
        phoneNumber: 5749229084,
        imgUrl: "https://www.subway.com/-/media/Base_English/Images/Branding/subway-logo-new-1200x630.png",
        rating: 3.1,
        tags: ["sandwich", "salad", "vegan"],
        menu: [],
    },

    {
        restaurant_id: "222",
        restaurantName: "KFC",
        apartmentNumber: 100,
        streetname: "Klien St",
        zipcode: 47382,
        phoneNumber: 3754320798,
        imgUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/KFC_logo.svg/200px-KFC_logo.svg.png",
        rating: 2.5,
        tags: ["fried chicken"],
        menu: [],
    },
    {
        restaurant_id: "789",
        restaurantName: "Taco Bell",
        apartmentNumber: 523,
        streetname: "Glover Dr",
        zipcode: 43321,
        phoneNumber: 5849312344,
        imgUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b3/Taco_Bell_2016.svg/150px-Taco_Bell_2016.svg.png",
        rating: 3.1,
        tags: ["tacos", "burritos", "quesadillas"],
        menu: [],
    },
];

module.exports = restaurants;